CREATE TABLE Jobs
(
	JobId INT PRIMARY KEY IDENTITY(1,1),
	JobTitle VARCHAR(30) DEFAULT ' ',
	MinSalary DECIMAL(5,0) DEFAULT 8000.00,
	MaxSalary DECIMAL(8,0) DEFAULT NULL
);

INSERT INTO Jobs VALUES ('Mobile Developer', 20000, 30000), ('.Net Developer', NULL, NULL), ('.Net Developer', NULL, 30000);

SELECT * FROM Jobs;

CREATE TABLE JobHistory
(
	EmployeeId INT PRIMARY KEY IDENTITY(1,1),
	StartDate VARCHAR(12) NOT NULL,
	EndDate VARCHAR(12) NOT NULL CHECK (EndDate LIKE '__/__/____'),
	JobId INT NOT NULL,
	DepartmentId INT NOT NULL
);

INSERT INTO JobHistory VALUES ('2021/22/02','22/02/2022', 1, 4);

SELECT * FROM JobHistory;

ALTER TABLE JobHistory ADD CONSTRAINT fk_JobId FOREIGN KEY (JobId) REFERENCES Jobs(JobId);

ALTER TABLE JobHistory DROP CONSTRAINT fk_JobId;

ALTER TABLE JobHistory ADD Location VARCHAR(20);