CREATE TABLE Jobs
(
	JobId INT UNIQUE IDENTITY(1,1),
	JobTitle VARCHAR(30) DEFAULT ' ',
	MinSalary DECIMAL(5,0) DEFAULT 8000.00,
	MaxSalary DECIMAL(8,0) DEFAULT NULL
);

INSERT INTO Jobs VALUES ('Mobile Developer', 20000, 30000), ('.Net Developer', NULL, NULL), ('.Net Developer', NULL, 30000);

SELECT * FROM Jobs;